#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Format the code with prettier..."
npx prettier --write .
echo "Checking the ESLint..."
yarn lint
echo "Building the project..."
yarn build
echo "Run unit testing..."
yarn test:ci
echo "Run e2e testing..."
yarn e2e:ci